# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Depaudit < Formula
  desc "Beautiful TUI for exploring JS dependency vulnerabilities"
  homepage "https://github.com/stevepapa/depaudit"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevepapa/depaudit/releases/download/v0.9.1/depaudit_0.9.1_darwin_amd64.tar.gz"
      sha256 "0d2ed29769d232c19fafe610e87e7f592f560fd5edeb1c448c7c8b2b5ae80111"

      def install
        bin.install "depaudit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevepapa/depaudit/releases/download/v0.9.1/depaudit_0.9.1_darwin_arm64.tar.gz"
      sha256 "8a4a32cf48ce25e6b32c2580abe9f38ddf3b7278547ebad65f23d5c5c0a161a1"

      def install
        bin.install "depaudit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevepapa/depaudit/releases/download/v0.9.1/depaudit_0.9.1_linux_amd64.tar.gz"
      sha256 "53d323d43cf3150e234f78500e76a7362bb524d4cb3c7c4d798c70f6d1bd19ff"
      def install
        bin.install "depaudit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevepapa/depaudit/releases/download/v0.9.1/depaudit_0.9.1_linux_arm64.tar.gz"
      sha256 "c702dc565c683dad224e3692cd5dbfd3f06c96234a81c361c2a3c98a2718e20b"
      def install
        bin.install "depaudit"
      end
    end
  end

  test do
    system "#{bin}/depaudit", "--version"
  end
end
