# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Depaudit < Formula
  desc "Beautiful TUI for exploring JS dependency vulnerabilities"
  homepage "https://github.com/stevepapa/depaudit"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stevepapa/depaudit/releases/download/v1.0.0/depaudit_1.0.0_darwin_amd64.tar.gz"
      sha256 "1e5af67aec871b35765c1d08ca6862b505f81c492b4ea509731a58e1e6d32704"

      def install
        bin.install "depaudit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stevepapa/depaudit/releases/download/v1.0.0/depaudit_1.0.0_darwin_arm64.tar.gz"
      sha256 "bf58853fc93f962ec87cf2f9fcfdd14994a54a0a115a3f99d818b9afcf8f4fbd"

      def install
        bin.install "depaudit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevepapa/depaudit/releases/download/v1.0.0/depaudit_1.0.0_linux_amd64.tar.gz"
      sha256 "ddde4c013c659974f92e195e6a8744013e4a2a003292b00dc436d6bc576b905d"
      def install
        bin.install "depaudit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stevepapa/depaudit/releases/download/v1.0.0/depaudit_1.0.0_linux_arm64.tar.gz"
      sha256 "bd8de00095a9e86ba96c7c107df8987bd858f687f7f3befe3004edf8e8ce0f95"
      def install
        bin.install "depaudit"
      end
    end
  end

  test do
    system "#{bin}/depaudit", "--version"
  end
end
